// 车次来源
export const dateTypes = [
    { text: '本月', key: '0' }, 
    { text: '上月', key: '1' }, 
    { text: '最近三月', key: '3' }
];
export function getCulomns (){
    return [
        {title: '运单号',key: 'order_no', width : 150}, 
        {title: '开单日期',key: 'order_create_time', width : 120}, 
        {title: '项目名称',key: 'prj_name', width : 150}, 
        {title: '收入合计',key: 'partner_fee', width : 150}, 
        {title: '支出合计',key: 'pay_fee', width : 100},
        {title: '运单毛利',key: 'income_fee', width : 100},
        {title: '干线运费（收入）',key: 'fee_transport', width : 150},
        {title: '提货费（收入）',key: 'partner_fee_th',width : 150},
        {title: '送货费（收入）',key: 'partner_fee_sh', width : 150},
        {title: '保价费（收入）',key: 'partner_fee_bj', width : 150},
        {title: '保险费（收入）',key: 'partner_fee_bx', width : 150},
        {title: '装卸费（收入）',key: 'partner_fee_zx', width : 150},
        {title: '上楼费（收入）',key: 'partner_fee_sl', width : 150},
        {title: '包装费（收入）',key: 'partner_fee_bz', width : 150},
        {title: '安装费（收入）',key: 'partner_fee_az', width : 150},
        {title: '保管费（收入）',key: 'partner_fee_bg', width : 150},
        {title: '进仓费（收入）',key: 'partner_fee_jc', width : 150},
        {title: '代收手续费（收入）',key: 'partner_fee_dssx', width : 150},
        {title: '其他费用（收入）',key: 'partner_fee_qt', width : 150},
        {title: '干线运费（支出）',key: 'pay_fee_transport', width : 150},
        {title: '油卡（支出）',key: 'liner_pay_oil', width : 150},
        {title: '提货费（支出）',key: 'liner_fee_th', width : 150},
        {title: '送货费（支出）',key: 'liner_fee_sh', width : 150},
        {title: '保价费（支出）',key: 'liner_fee_bj', width : 150},
        {title: '保险费（支出）',key: 'liner_fee_bx', width : 150},
        {title: '装卸费（支出）',key: 'liner_fee_zx', width : 150},
        {title: '上楼费（支出）',key: 'liner_fee_sl', width : 150},
        {title: '包装费（支出）',key: 'liner_fee_bz', width : 150},
        {title: '安装费（支出）',key: 'liner_fee_az', width : 150},
        {title: '保管费（支出）',key: 'liner_fee_bg', width : 150},
        {title: '进仓费（支出）',key: 'liner_fee_jc', width : 150},
        {title: '代收手续费（支出）',key: 'liner_fee_dssx', width : 150},
        {title: '其他费用（支出）',key: 'liner_fee_qt', width : 150},
        {title: '客户名称',key: 'send_company', width : 120},
        {title: '发货人',key: 'begin_link_man', width : 120},
        {title: '发货人联系方式',key: 'begin_link_mobile', width : 120},
        {title: '承运人',key: 'common_carrier', width : 120},
        {title: '落货网点',key: 'arrive_company_name', width : 120},
        {title: '货物名称',key: 'cargos_name', width : 180},
        {title: '总重量（T）',key: 'order_weights', width : 120},
        {title: '总体积（方）',key: 'order_volumes', width : 120},
        {title: '始发',key: 'begin_area', width : 150},
        {title: '到达',key: 'end_area', width : 150},
        {title: '是否提货',key: 'was_pickup_desc', width : 120},
        {title: '是否送货',key: 'was_delivery_desc', width : 120},
        {title: '创建时间',key: 'create_time', width : 120},
        {title: '签收时间',key: 'sign_date', width : 120},
        {title: '回单状态',key: 'back_state_desc', width : 120},
        {title: '备注',key: 'shipper_remark', width : 120}
    ]
}

//运单毛利总计列表
export function getTotalCulomns (){
    return [
        {title: '运单数总计',key: 'order_total', width : 100},
        {title: '运单毛利总计',key: 'income_fee_total', width : 120},
        {title: '支出总计',key: 'pay_fee_total', width : 130}, 
        {title: '收入总计',key: 'partner_fee_total', width : 130}, 
        {title: '干线运费总计（收入）',key: 'fee_transport_total', width : 180},
        {title: '提货费总计（收入）',key: 'partner_fee_th_total',width : 150},
        {title: '送货费总计（收入）',key: 'partner_fee_sh_total', width : 150},
        {title: '保价费总计（收入）',key: 'partner_fee_bj_total', width : 150},
        {title: '保险费总计（收入）',key: 'partner_fee_bx_total', width : 150},
        {title: '装卸费总计（收入）',key: 'partner_fee_zx_total', width : 150},
        {title: '上楼费总计（收入）',key: 'partner_fee_sl_total', width : 150},
        {title: '包装费总计（收入）',key: 'partner_fee_bz_total', width : 150},
        {title: '安装费总计（收入）',key: 'partner_fee_az_total', width : 150},
        {title: '保管费总计（收入）',key: 'partner_fee_bg_total', width : 150},
        {title: '进仓费总计（收入）',key: 'partner_fee_jc_total', width : 150},
        {title: '代收手续费总计（收入）',key: 'partner_fee_dssx_total', width : 180},
        {title: '其他费用总计（收入）',key: 'partner_fee_qt_total', width : 170},
        {title: '干线运费总计（支出）',key: 'pay_fee_transport_total', width : 170},
        {title: '提货费总计（支出）',key: 'liner_fee_th_total', width : 150},
        {title: '送货费总计（支出）',key: 'liner_fee_sh_total', width : 150},
        {title: '保价费总计（支出）',key: 'liner_fee_bj_total', width : 150},
        {title: '保险费总计（支出）',key: 'liner_fee_bx_total', width : 150},
        {title: '装卸费总计（支出）',key: 'liner_fee_zx_total', width : 150},
        {title: '上楼费总计（支出）',key: 'liner_fee_sl_total', width : 150},
        {title: '包装费总计（支出）',key: 'liner_fee_bz_total', width : 150},
        {title: '安装费总计（支出）',key: 'liner_fee_az_total', width : 150},
        {title: '保管费总计（支出）',key: 'liner_fee_bg_total', width : 150},
        {title: '进仓费总计（支出）',key: 'liner_fee_jc_total', width : 150},
        {title: '进仓手续费总计（支出）',key: 'liner_fee_dssx_total', width : 180},
        {title: '其他费用总计（支出）',key: 'liner_fee_qt_total', width : 170},
        {title: '总重量（T）',key: 'order_weights_total', width : 120},
        {title: '总体积（方）',key: 'order_volumes_total', width : 120}
    ]
}

